In [1]:
import pandas as pd
d=pd.read_csv("student_admission_record_dirty.csv")

In [2]:
d.head()

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,Shehroz,24.0,Female,50.0,68.90,Quetta,Rejected
1,Waqar,21.0,Female,99.0,60.73,Karachi,NaN
2,Bushra,17.0,Male,89.0,NaN,Islamabad,Accepted
3,Aliya,17.0,Male,55.0,85.29,Karachi,Rejected
4,Bilal,20.0,Male,65.0,61.13,Lahore,NaN

In [3]:
d.head(3)

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,Shehroz,24.0,Female,50.0,68.90,Quetta,Rejected
1,Waqar,21.0,Female,99.0,60.73,Karachi,NaN
2,Bushra,17.0,Male,89.0,NaN,Islamabad,Accepted

In [4]:
d.tail()

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
152,Ali,19.0,Female,85.0,78.09,Quetta,Accepted
153,Bilal,17.0,Female,81.0,84.40,Islamabad,Rejected
154,Fatima,21.0,Female,98.0,50.86,Multan,Accepted
155,Shoaib,-1.0,Male,91.0,80.12,Quetta,Accepted
156,Maaz,17.0,Male,88.0,86.85,Lahore,Accepted

In [5]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    147 non-null    object
 1   Age                     147 non-null    float64
 2   Gender                  147 non-null    object
 3   Admission Test Score    146 non-null    float64
 4   High School Percentage  146 non-null    float64
 5   City                    147 non-null    object
 6   Admission Status        147 non-null    object
dtypes: float64(3), object(4)
memory usage: 6.2+ KB

In [6]:
d.isnull().head()

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True
2,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True

In [10]:
d.isnull().sum()

Name                      10
Age                       10
Gender                    10
Admission Test Score      11
High School Percentage    11
City                      10
Admission Status          10
dtype: int64

In [11]:
d.head(2)

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,Shehroz,24.0,Female,50.0,68.90,Quetta,Rejected
1,Waqar,21.0,Female,99.0,60.73,Karachi,NaN

In [24]:
import numpy as n
d["High School Percentage"].replace(' ',n.nan,inplace=True)

<ipython-input-24-bd1a3da2eee9>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d["High School Percentage"].replace(' ',n.nan,inplace=True)

In [25]:
d.isnull().sum()

Name                      10
Age                       10
Gender                    10
Admission Test Score      11
High School Percentage    11
City                      10
Admission Status          10
dtype: int64

In [27]:
d["High School Percentage"] = pd.to_numeric(d["High School Percentage"], errors="coerce")
d["High School Percentage"].fillna(d["High School Percentage"].mean(),inplace=True)

<ipython-input-27-9a02cbadf286>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d["High School Percentage"].fillna(d["High School Percentage"].mean(),inplace=True)

In [29]:
d["High School Percentage"]

0      68.900000
1      60.730000
2      75.684726
3      85.290000
4      61.130000
         ...
152    78.090000
153    84.400000
154    50.860000
155    80.120000
156    86.850000
Name: High School Percentage, Length: 157, dtype: float64

In [30]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
d["Gender-encoded"]=le.fit_transform(d["Gender"])
d["Gender-encoded"],d["Gender"]

(0      0
 1      0
 2      1
 3      1
 4      1
       ..
 152    0
 153    0
 154    0
 155    1
 156    1
 Name: Gender-encoded, Length: 157, dtype: int32,
 0      Female
 1      Female
 2        Male
 3        Male
 4        Male
         ...
 152    Female
 153    Female
 154    Female
 155      Male
 156      Male
 Name: Gender, Length: 157, dtype: object)